### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by ericklil** [tananaev/traccar#1006]
Installing traccar on mac 64 bit leaves the following terminal issues: sudo: ./traccar.run: command not found.
I am rather unfamiliar with terminal and the installation process. Guess i am making a basic mistake however any pointing in the right direction would be very much appreciated! Many Thanks!

**Comment by ericklil** [comment]
Hello again,
Trying to install on a new server gave me the following errors:

WARNING: traccar may have failed to start.
server:~ ericko$

**Comment by tananaev** [comment]
Check wrapper.log file for the detailed error message.

**Comment by ericklil** [comment]
Many Thanks!

**Comment by luiramji** [comment]
Hi, I have the same problem. The wrapper.log file shows: "The configured wrapper.java.command could not be found, attempting to launch anyway: java"

**Comment by tananaev** [comment]
It means you don't have java installed or environment variables are not set correctly. What OS are you using?

**Comment by luiramji** [comment]
Sorry, I was missing java. Solved. Thanks.

**Comment by luiramji** [comment]
Well now It starts but stop because: (Wrapper log) "NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet"

**Comment by tananaev** [comment]
Ignore warning about JSP. If it stops then there must some other reason for that.

**Comment by luiramji** [comment]
...by the way, I am using CentOS 5.10.

**Comment by luiramji** [comment]
Well I have this at wrapper log:

"INFO   | jvm 1    | 2015/01/18 19:33:04 | 2015-01-18 19:33:04.246:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
INFO   | jvm 1    | 2015/01/18 19:33:04 | 2015-01-18 19:33:04.346:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:8082
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp: 
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: org.jboss.netty.channel.ChannelException: Failed to bind to: 0.0.0.0/0.0.0.0:5038
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.jboss.netty.bootstrap.ServerBootstrap.bind(ServerBootstrap.java:272)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.traccar.TrackerServer.start(TrackerServer.java:130)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.traccar.ServerManager.start(ServerManager.java:191)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.traccar.Main.main(Main.java:32)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at java.lang.reflect.Method.invoke(Method.java:622)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:290)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at java.lang.Thread.run(Thread.java:701)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: Caused by: java.net.BindException: La dirección ya se está usando
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at sun.nio.ch.Net.bind0(Native Method)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at sun.nio.ch.Net.bind(Net.java:174)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:139)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:77)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss$RegisterTask.run(NioServerBoss.java:193)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.processTaskQueue(AbstractNioSelector.java:391)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:315)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2015/01/18 19:33:04 | WrapperSimpleApp Error: 	... 1 more
"

**Comment by tananaev** [comment]
Looks like you have some other app listening on port 5038.

**Comment by luiramji** [comment]
Thanks, you were right. I changed and it is up and running. I really love your product, I am new to linux and I am testing it, many thanks for your immediate help. Just one more thing, do you know any way to  check what is using the 5038 port?

**Comment by tananaev** [comment]
You can use `netstat` to check what process is listening on what port.

**Comment by luiramji** [comment]
Thanks
