### ISSUE TITLE
Protocol VJOY

### ISSUE THREAD

**Issue by Xav59** [tananaev/traccar#1097]
Hi,

I have a new set of GPS devices from the VJOY company (http://www.vjoycar.com/gps-tracker-battery/asset-gps-tracker.html).
They gave me the specifications of their protocol which looks pretty similar to the TK103.
Here below an extract of what seems to be useful. I can send the whole document.

I'm not an expert java developer, but I think I can develop the decoder from the TK103 one. I'd be glad to help you. Shall I do that so you could just validate and integrate it? Or do you prefer to work another way?

Xavier

**Comment by tananaev** [comment]
Please send me the whole document (email address is in GitHub profile).

**Comment by tananaev** [comment]
I think TK103 protocol should work for this device. Try port 5002.

**Comment by Xav59** [comment]
I have seen some differences with TK103, mainly :
- the "registration" is using command ZC01 instead of BP00
- the answer to the device should be "ok"

I will try TK103 anyway this week and let you know about the results.

Thanks

2015-02-24 22:59 GMT+01:00 Anton Tananaev <notifications@github.com>:

**Comment by tananaev** [comment]
Messages from the log file that you sent me are binary and do not match protocol documentation you gave me earlier.

**Comment by Xav59** [comment]
???
I did not send you any log. The tracker is in use so I could not test it for the moment. I only gave you the protocol documentation.
I'll let you know the result of the test with the TK103 protocol as soon as the tracker is back so I can test it.

**Comment by tananaev** [comment]
Sorry, someone else send me logs through email and mentioned this post.

**Comment by Xav59** [comment]
No problem ;-)
Le 28 févr. 2015 21:01, "Anton Tananaev" <notifications@github.com> a écrit
:

**Comment by orezzz** [comment]
Hi!
Can you please send me this spec too. I have vjoy watch tracker and would like to recieve data by my own server.
My email is in profile. Thanks!

**Comment by Xav59** [comment]
Documentation is sent.
I didn't have the opportunity to test the protocol as the tracker is
already in use. I'll work on it as soon as it's back.

2015-05-21 13:05 GMT+02:00 orezzz <notifications@github.com>:

**Comment by orezzz** [comment]
Thank you very much!

**Comment by Xav59** [comment]
I have at least be able to do some tests with my VJOY.
Protocol TK103 is working, even if it cannot manage all the available informations in all types of messages (as the battery level for example).
So I close this issue, thanks for your advice :)

**Comment by aponcel** [comment]
Hi Guys, I have the T8800 GPS from Vjoycar vendor (http://www.vjoycar.com/gps-tracker-battery/GPS-Tracker-Battery.html) with the same issue of how show the battery status. I work with the version 2.11 of the traccar server.

Do you know if with the last version this issue is fixed? and if showing the battery status from GPS devices connected.

Kindly Regards.

**Comment by tananaev** [comment]
@aponcel, please provide HEX message samples from your device for me to check if it includes battery info.

**Comment by aponcel** [comment]
Hi Anton,

    Thanks for the fast answer, here's a line for the battery status:

2015-10-29 00:03:31 DEBUG: [5002 <- 192.168.1.50] - HEX: 283836343736383031303135393738352c5a4332302c3239313031352c3033303431332c332c3336322c36353533352c32353529

    With the tool HEX to DEC (https://www.traccar.org/hex-decoder/) this is the result:

(864768010159785,ZC20,291015,030413,3,362,65535,255)

   The protocol (http://www.vjoycar.com/Up/day_150610/Revised%20Protocol%20150306.pdf) of vjoycar vendor saying:

----------------------------------------------------------------------------------
1.11 Battery Level(ZC20)

(013632651491, ZC20,040613,040137,6,42,112,0)

"("            stands for packet start
"013632651491" stands for tracker ID
" ZC20"        stands for battery level command
"040613"       stands for data, 04/June/2013
"040137"       stands for time, 04:01:37, UTC time
"6"            stands for battery level, range is 0-6, 255 refers to invalid rate
"421"          stands for battery voltage, eg 4.21V, 65535 refers to invalid rate
"112"          stands for battery input voltage, eg11.2V, 65535 refers to invalid rate
"0"            stands for not installed(0) or installed(1), 255 refers to invalid rate
")"            stands for packet end
----------------------------------------------------------------------------------

    In the sample of the protocol, the status battery value is 6, for the real case is 3 but this value i can't get it in the traccar v2.11.

    Do you know if is possible show this battery value in GPS device in the map or in a tooltip?

Kindly Regards

Kindly Regards

**Comment by tananaev** [comment]
I have added support for messages with battery info. Here is a new build:

https://www.dropbox.com/s/myt68q5u7fiz49r/tracker-server-jar-with-dependencies.jar?dl=0

**Comment by aponcel** [comment]
Hi Anton,

    Thanks so much for this fix!!!, I tell you later if it works fine.

Kindly Regards

**Comment by aponcel** [comment]
Hi Anton, I tried deploy the jar file in the server for this I made a backup of the file /opt/traccar/tracker-server.jar and replaced that file with your file tracker-server-jar-with-dependencies.jar.

cp tracker-server-jar-with-dependencies.jar /opt/traccar/tracker-server.jar

The next step is start the server:

sudo /opt/traccar/bin/traccar start

But the web interface is not started, this is the registry for the log cat /opt/traccar/logs/wrapper.log.20151102

------------------------------------
STATUS | wrapper  | 2015/11/02 16:00:13 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/11/02 16:00:13 | Java Service Wrapper Community Edition 64-bit 3.5.25
STATUS | wrapper  | 2015/11/02 16:00:13 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/11/02 16:00:13 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/11/02 16:00:13 |
STATUS | wrapper  | 2015/11/02 16:00:13 | Launching a JVM...
INFO   | jvm 1    | 2015/11/02 16:00:13 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/11/02 16:00:14 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/11/02 16:00:14 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/11/02 16:00:14 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9c1jxfrofb9rq0s|a5061b, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> com.mysql.jdbc.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9c1jxfrofb9rq0s|a5061b, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:mysql://192.168.1.171:3306/traccar?allowMultiQueries=true&autoReconnect=true&useUnicode=yes&characterEncoding=UTF-8&sessionVariables=sql_mode=ANSI_QUOTES, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
------------------------------------

Here's other log:

------------------------------------
root@traccarfix:/opt/traccar# cat /opt/traccar/logs/tracker-server.log
2015-11-02 15:29:41  INFO: Starting server...
2015-11-02 15:29:41  INFO: Operating System name: Linux version: 3.16.0-30-generic architecture: amd64
2015-11-02 15:29:41  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2015-11-02 15:29:41  INFO: Memory Limit heap: 481mb non-heap: 214mb
2015-11-02 15:29:41  INFO: Version: 2.11-SNAPSHOT
2015-11-02 15:33:35  INFO: Shutting down server...
2015-11-02 15:37:40  INFO: Starting server...
2015-11-02 15:37:40  INFO: Operating System name: Linux version: 3.16.0-30-generic architecture: amd64
2015-11-02 15:37:40  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2015-11-02 15:37:40  INFO: Memory Limit heap: 481mb non-heap: 214mb
2015-11-02 15:37:40  INFO: Version: 2.11-SNAPSHOT
2015-11-02 15:38:18  INFO: Shutting down server...
2015-11-02 15:38:40  INFO: Starting server...
2015-11-02 15:38:40  INFO: Operating System name: Linux version: 3.16.0-30-generic architecture: amd64
2015-11-02 15:38:40  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2015-11-02 15:38:40  INFO: Memory Limit heap: 481mb non-heap: 214mb
2015-11-02 15:38:40  INFO: Version: 2.11-SNAPSHOT
2015-11-02 15:40:02  INFO: Shutting down server...
2015-11-02 15:49:57  INFO: Starting server...
2015-11-02 15:49:57  INFO: Operating System name: Linux version: 3.16.0-30-generic architecture: amd64
2015-11-02 15:49:57  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2015-11-02 15:49:57  INFO: Memory Limit heap: 481mb non-heap: 214mb
2015-11-02 15:49:57  INFO: Version: 2.11-SNAPSHOT
2015-11-02 15:50:51  INFO: Shutting down server...
2015-11-02 15:51:56  INFO: Starting server...
2015-11-02 15:51:56  INFO: Operating System name: Linux version: 3.16.0-30-generic architecture: amd64
2015-11-02 15:51:56  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2015-11-02 15:51:56  INFO: Memory Limit heap: 481mb non-heap: 214mb
2015-11-02 15:51:56  INFO: Version: 2.11-SNAPSHOT
2015-11-02 15:55:29  INFO: Shutting down server...
2015-11-02 15:56:50  INFO: Starting server...
2015-11-02 15:56:50  INFO: Operating System name: Linux version: 3.16.0-30-generic architecture: amd64
2015-11-02 15:56:50  INFO: Java Runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2015-11-02 15:56:50  INFO: Memory Limit heap: 481mb non-heap: 214mb
2015-11-02 15:56:50  INFO: Version: 2.11-SNAPSHOT
2015-11-02 15:58:46  INFO: Shutting down server...
2015-11-02 16:00:14  INFO: Operating system name: Linux version: 3.16.0-30-generic architecture: amd64
2015-11-02 16:00:14  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 24.85-b03
2015-11-02 16:00:14  INFO: Memory limit heap: 481mb non-heap: 214mb
2015-11-02 16:00:14  INFO: Character encoding: UTF-8 charset: UTF-8
2015-11-02 16:00:14  INFO: Version: null
2015-11-02 16:00:14  INFO: Query not provided: database.createSchema
2015-11-02 16:00:14  INFO: Query not provided: database.insertUser
2015-11-02 16:00:14  INFO: Query not provided: database.insertServer
2015-11-02 16:00:14  INFO: Query not provided: database.selectLatestPositions
2015-11-02 16:00:15  INFO: Starting server...
------------------------------------

I hope you can help me with this.

Kindly Regards

**Comment by tananaev** [comment]
It looks like Traccar can't connect to the database.

**Comment by aponcel** [comment]
Hi Anton, 

Uhmm let's stated.

* Traccar Server Status
------------------
root@traccarfix:/opt/traccar# /opt/traccar/bin/traccar status
traccar is running: PID:14536, Wrapper:STARTED, Java:STARTED
-----------------------

* Traccar Configuration
-----------------------
root@traccarfix:/opt/traccar# cat /opt/traccar/conf/traccar.cfg
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    
    <entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.url'>jdbc:mysql://192.168.1.171:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
    <entry key='database.user'>admin</entry>
    <entry key='database.password'>admin</entry>


    
    <entry key='database.selectDevice'>
        SELECT id, uniqueId as imei
        FROM devices;
    </entry>

    
    <entry key='database.insertPosition'>
        INSERT INTO positions (device_id, time, valid, latitude, longitude, altitude, speed, course, power, address, other)
        VALUES (:device_id, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :power, :address, :extended_info);
    </entry>

    
    <entry key='database.updateLatestPosition'>
        UPDATE devices SET latestPosition_id = :id WHERE id = :device_id;
    </entry>

    
    <entry key='http.enable'>true</entry>
    
    <entry key='http.port'>8082</entry>
    <entry key='http.application'>/opt/traccar/traccar-web.war</entry>

    
    <entry key='geocoder.enable'>false</entry>
    <entry key='geocoder.type'>nominatim</entry>
    <entry key='geocoder.url'>http://nominatim.openstreetmap.org/reverse</entry>

    
    

    
    <entry key='logger.enable'>true</entry>
    <entry key='logger.level'>all</entry>
    <entry key='logger.file'>/opt/traccar/logs/tracker-server.log</entry>

    
    <entry key='detector.enable'>true</entry>
    <entry key='detector.port'>5000</entry>
...
-----------------------

* Database Status and connection 
-----------------------
root@traccarfix:/opt/traccar# service mysql status
 * /usr/bin/mysqladmin  Ver 9.0 Distrib 5.5.44-MariaDB, for debian-linux-gnu on x86_64
Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Server version          5.5.44-MariaDB-1ubuntu0.14.04.1
Protocol version        10
Connection              Localhost via UNIX socket
UNIX socket             /var/run/mysqld/mysqld.sock
Uptime:                 1 hour 38 min 54 sec

Threads: 4  Questions: 1083  Slow queries: 0  Opens: 99  Flush tables: 2  Open tables: 50  Queries per second avg: 0.182
root@traccarfix:/opt/traccar# mysql -uadmin -padmin -h192.168.1.171
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 653
Server version: 5.5.44-MariaDB-1ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| performance_schema |
| traccar            |
+--------------------+
4 rows in set (0.00 sec)

MariaDB [(none)]> use traccar;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [traccar]> show tables;
+-----------------------+
| Tables_in_traccar     |
+-----------------------+
| application_settings  |
| devices               |
| events                |
| notification_settings |
| positions             |
| ui_state              |
| user_settings         |
| users                 |
| users_devices         |
+-----------------------+
9 rows in set (0.00 sec)

MariaDB [(none)]> quit
Bye
root@traccarfix:/opt/traccar#
-----------------------

* Conectivity with port 8082 (Failed)
-----------------------
root@traccarfix:/opt/traccar# telnet 127.0.0.1 8082
Trying 127.0.0.1...
telnet: Unable to connect to remote host: Connection refused
root@traccarfix:/opt/traccar#
-----------------------

I think all fine, the traccar service it´s started but I dont know it may be happening.

Do you have any idea?

Kindly Regards

**Comment by tananaev** [comment]
I'm pretty sure that the problem is with database connection. I would recommend to try with original H2 database and see if it works.

**Comment by aponcel** [comment]
Hi Anton, Thanks for you help!!!, Well I tried with the H2 database, but the result its the same.

* Traccar configuration file
------------------------
root@traccarfix:/opt/traccar/conf# cat /opt/traccar/conf/traccar.cfg
<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    
    <entry key='database.driver'>org.h2.Driver</entry>
    <entry key='database.url'>jdbc:h2:/opt/traccar/data/database</entry>
    <entry key='database.user'>sa</entry>
    <entry key='database.password'></entry>

    
    <entry key='database.selectDevice'>
        SELECT id, uniqueId as imei
        FROM devices;
    </entry>

    
    <entry key='database.insertPosition'>
        INSERT INTO positions (device_id, time, valid, latitude, longitude, altitude, speed, course, power, address, other)
        VALUES (:device_id, :time, :valid, :latitude, :longitude, :altitude, :speed, :course, :power, :address, :extended_info);
    </entry>

    
    <entry key='database.updateLatestPosition'>
        UPDATE devices SET latestPosition_id = :id WHERE id = :device_id;
    </entry>

    
    <entry key='http.enable'>true</entry>
    
    <entry key='http.port'>8082</entry>
    <entry key='http.application'>/opt/traccar/traccar-web.war</entry>
...
------------------------

* Traccar Log
-----------------------
root@traccarfix:# cat  /opt/traccar/logs/wrapper.log.20151102

STATUS | wrapper  | 2015/11/02 17:55:07 | --> Wrapper Started as Daemon
STATUS | wrapper  | 2015/11/02 17:55:07 | Java Service Wrapper Community Edition 64-bit 3.5.25
STATUS | wrapper  | 2015/11/02 17:55:07 |   Copyright (C) 1999-2014 Tanuki Software, Ltd. All Rights Reserved.
STATUS | wrapper  | 2015/11/02 17:55:07 |     http://wrapper.tanukisoftware.com
STATUS | wrapper  | 2015/11/02 17:55:07 |
STATUS | wrapper  | 2015/11/02 17:55:07 | Launching a JVM...
INFO   | jvm 1    | 2015/11/02 17:55:07 | WrapperManager: Initializing...
INFO   | jvm 1    | 2015/11/02 17:55:07 | [MLog-Init-Reporter] INFO com.mchange.v2.log.MLog - MLog clients using slf4j logging.
INFO   | jvm 1    | 2015/11/02 17:55:07 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5.1 [built 16-June-2015 00:06:36 -0700; debug? true; trace: 10]
INFO   | jvm 1    | 2015/11/02 17:55:08 | [WrapperSimpleAppMain] INFO com.mchange.v2.c3p0.impl.AbstractPoolBackedDataSource - Initializing c3p0 pool... com.mchange.v2.c3p0.ComboPooledDataSource [ acquireIncrement -> 3, acquireRetryAttempts -> 30, acquireRetryDelay -> 1000, autoCommitOnClose -> false, automaticTestTable -> null, breakAfterAcquireFailure -> false, checkoutTimeout -> 0, connectionCustomizerClassName -> null, connectionTesterClassName -> com.mchange.v2.c3p0.impl.DefaultConnectionTester, contextClassLoaderSource -> caller, dataSourceName -> z8kfsx9c1k1jixe1uuuzz9|18244c45, debugUnreturnedConnectionStackTraces -> false, description -> null, driverClass -> org.h2.Driver, extensions -> {}, factoryClassLocation -> null, forceIgnoreUnresolvedTransactions -> false, forceSynchronousCheckins -> false, forceUseNamedDriverClass -> false, identityToken -> z8kfsx9c1k1jixe1uuuzz9|18244c45, idleConnectionTestPeriod -> 600, initialPoolSize -> 3, jdbcUrl -> jdbc:h2:/opt/traccar/data/database, maxAdministrativeTaskTime -> 0, maxConnectionAge -> 0, maxIdleTime -> 0, maxIdleTimeExcessConnections -> 0, maxPoolSize -> 15, maxStatements -> 0, maxStatementsPerConnection -> 0, minPoolSize -> 3, numHelperThreads -> 3, preferredTestQuery -> null, privilegeSpawnedThreads -> false, properties -> {user=******, password=******}, propertyCycle -> 0, statementCacheNumDeferredCloseThreads -> 0, testConnectionOnCheckin -> true, testConnectionOnCheckout -> false, unreturnedConnectionTimeout -> 0, userOverrides -> {}, usesTraditionalReflectiveProxies -> false ]
-----------------------


When recover the backup file "tracker-server.jar" and I tried connect with MySQL or H2 and the server works fine with this I can access perfect for web page, maybe I need other step for the correct deploy.

For this I only assumed that's the correct form (replace the tracker-server.jar with the new file attached in dropbox)

Best Regards

**Comment by tananaev** [comment]
What version of Traccar did you have before? I just realized that you have an old one. You need to install version 3.1 first and then replace JAR file with the one I provided.

**Comment by aponcel** [comment]
Upss!!!, the test was made in the traccar 2.11, because I have a production server with this version (25 GPS connected).


 but what do you think,  it's a good idea migrate to the last version? or I can get this fix for version 2.11?

Thank very much for you help, I wait you answer because is very important for me.

Best Regards

**Comment by tananaev** [comment]
Migration is not that easy if you want to use new web interface, but it's fairly simple if you want to continue using old web interface. In the long term, I guess you would have to update eventually.

Some more info about upgrading:
https://www.traccar.org/update-from-2-x-to-3-0/
https://www.traccar.org/update-from-3-0-to-3-1/

**Comment by aponcel** [comment]
Anton Thanks for you answer!!!, now I deployed the fix in traccar 3.1 and work fine!!!, I tell you the result.

The GPS device send this information

2015-11-03 11:54:13 DEBUG: [084FB14B: 5002 < 192.168.1.50] HEX: 283836343736383031303135393738352c5a4330372c3033313131352c412c333332362e3538373431532c30373033372e3931373036572c302e3138362c3134353431322c3030302e3029283836343736383031303135393738352c5a4332302c3033313131352c3134353433312c322c3334322c36353533352c32353529 
2015-11-03 11:54:14  INFO: [084FB14B] id: 7, time: Tue Nov 03 11:49:16 CLT 2015, lat: -33.4432345, lon: -70.632099, speed: 0.05399570000000001, course: 0.0
2015-11-03 11:54:14  INFO: [084FB14B] id: 7, time: Tue Nov 03 11:54:12 CLT 2015, lat: -33.4431235, lon: -70.631951, speed: 0.05399570000000001, course: 0.0


The package contains this information (HEX --> DEC)


HEX | DECIMAL
------- | -------
283836343736383031303135393738352c5a4330372c3033313131352c412c333332362e3538373431532c30373033372e3931373036572c302e3138362c3134353431322c3030302e3029283836343736383031303135393738352c5a4332302c3033313131352c3134353433312c322c3334322c36353533352c32353529 | (864768010159785,ZC07,031115,A,3326.58741S,07037.91706W,0.186,145412,000.0)(864768010159785,ZC20,031115,145431,2,342,65535,255)

In the database I see this

root@traccar31:~# mysql -uadmin -p
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 51
Server version: 5.5.44-MariaDB-1ubuntu0.14.04.1 (Ubuntu)

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use traccar;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [traccar]> SELECT
    -> id,
    -> protocol,
    -> servertime,
    -> fixtime,
    -> latitude,
    -> longitude,
    -> other
    -> FROM position
    -> WHERE
    -> deviceid = 7
    -> AND servertime = '2015-11-03 11:54:14';
+----+----------+---------------------+---------------------+----------+-----------+----------------------------------------------------------+
| id | protocol | servertime          | fixtime             | latitude | longitude | other                                                    |
+----+----------+---------------------+---------------------+----------+-----------+----------------------------------------------------------+
| 62 | tk103    | 2015-11-03 11:54:14 | 2015-11-03 11:49:16 | -33.4432 |  -70.6321 | <info><battery>342</battery><ip>192.168.1.50</ip></info> |
| 63 | tk103    | 2015-11-03 11:54:14 | 2015-11-03 11:54:12 | -33.4431 |   -70.632 | <info><ip>192.168.1.50</ip></info>                       |
+----+----------+---------------------+---------------------+----------+-----------+----------------------------------------------------------+
2 rows in set (0.00 sec)

MariaDB [traccar]>

In the column "other" contains the data of battery, thats great!!! but we can get more data about batterry because we have a only data of charge of the batterry (Voltage).

The protocol contains more data.

(864768010159785,
ZC20,
031115,
145431,
2,					--> Battery Level (1 to 6)
342,				--> Battery Voltage (V)
65535,				--> Input Voltage Battery (V)
255)

In this case we only have the Battery Voltage (V) in the column "other".

You can help me with add this values in the fix?

- [ ] 2,         --> Battery Level (1 to 6)
- [x] 342,	    --> Battery Charge Voltage (V)
- [ ] 65535, --> Input Voltage Battery (V)

Ohh! I forgot ask you if in traccar 3.1 I can see the battery information in the panel status how parametre? (with the information the column other)

Really thank for all!!!! :blush::blush::blush:

Best Regards

**Comment by tananaev** [comment]
Input voltage is already supported. Value 65535 means no value, so it's ignored in your case.

As for battery level, what's the point of having both level and voltage and what does level mean?

**Comment by aponcel** [comment]
Hi Anton, in the documentation protocol of the (GPS http://www.vjoycar.com/Up/day_150610/Revised%20Protocol%20150306.pdf) say the value 65535 is invalid range but the GPS sent other values how you can see now:

1.11 Battery Level(ZC20)
“112”  stands for battery input voltage, eg11.2V，65535 refers to invalid rate

Just in this case I get a bad info for the example, but I ask you this fix? the answer is because that GPS have a input to connect to dynamo and here's geting power and with this value I can know the bad dynamo.

![gps_open_sim](https://cloud.githubusercontent.com/assets/15387866/10921280/64c96c58-8253-11e5-8f94-32c41496c0c3.jpg)

Now the level battery is effective for threshold of monitoring.

Level | Charge
-------|-------------
6 | 100%
5 | 83%
4 | 66%
3 | 50%
2 | 33%
1 | 16%

The formule is:

((<level_battery>*100)/6)

I hope I responded. :smiley: :smiley: :smiley:

Best Regards

**Comment by tananaev** [comment]
If you don't see the value, it means it's invalid.

I will think about the battery level, but it seems like redundant information as level is calculated based on the voltage anyway.

**Comment by aponcel** [comment]
OK, that's right!!! thanks for your help!!! but I needed the input volt for monitoring the dynamos.

I think do you have a lot of work and issues that waiting for you and I understand your if you not can help me with this.

Really thanks for all!!!

Best Regards.

**Comment by tananaev** [comment]
Input Voltage is already supported.

**Comment by jcroman-itch** [comment]
Hi anton

I want to use your tracker-server-with-dependencies.jar file to display the battery level of my Vjoy gps tracker in my traccar server but I have a few question about this.

I need to replace the C:\Program Files (x86)\Traccar\traccar-server.jar with traccar-server-with-dependencies.jar or what I need to do?

By the way, my Vjoy tracker use tk103 protocol.

I hope you can help me.

**Comment by tananaev** [comment]
@jcroman-itch, you can just use version 3.2. It already includes the changes.

**Comment by jcroman-itch** [comment]
Thanks for the reply Anton.

It's strange because I already use the version 3.2 but the battery level is not displayed. 

The HEX file is
283836343736383031303532323230362c425030352c3139313231352c412c323833382e38323836304e2c31303630312e3237333032572c302e3033392c3137333735322c3030302e3029283836343736383031303532323230362c425030352c3139313231352c412c323833382e38333036394e2c31303630312e3237343630572c322e3930322c3137333830322c3335312e323629283836343736383031303532323230362c425030352c3139313231352c412c323833382e38323930384e2c31303630312e3237373436572c342e3033302c3137333831322c3231392e393829283836343736383031303532323230362c425030352c3139313231352c412c323833382e38313233324e2c31303630312e3239333830572c31302e3539302c3137333832322c3230372e313229283836343736383031303532323230362c425030352c3139313231352c412c323833382e37393037354e2c31303630312e3330393131572c362e3435322c3137333833322c3233362e313129283836343736383031303532323230362c425030352c3139313231352c412c323833382e37393937394e2c31303630312e3334303739572c31352e3032392c3137333834322c3239382e383229.

You think is device problem?

**Comment by tananaev** [comment]
That's because your device doesn't send battery information.

**Comment by jcroman-itch** [comment]
Ok anton, thanks for your help.
