### ISSUE TITLE
Questions on Users/Devices/Groups

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#1923]
In the model, I see that devices and groups are associated (linked) with users.  And, it appears that a hierarchy of groups can be created.  Please confirm.
1. What are the use-cases for groups?
2. Can I use groups to model "accounts" where users and devices are assigned to an account?  In this case, users do not carry devices; they manage them.  I would want all users of an account to be able to see all devices assigned to the account.

\- jss

**Comment by tananaev** [comment]
Groups are collection of devices. You can create hierarchy of groups as well. Very similar to how file system works. You have folders (groups) and files (devices).

Originally I wanted to show groups and devices as tree, but because of some issues in ExtJS library I could implement it. Instead for now I've added a field to filter by groups.

Benefits of using groups:

1. Simplify sharing of multiple devices between users. Instead of adding each device separately, you can just assign a group of device to a user.
2. Easier to search and filter devices by groups. Especially relevant for users with large number of devices.

**Comment by methmal59** [comment]
You said 
1, Simplify sharing of multiple devices between users. Instead of adding each device separately, you can just assign a group of device to a user.

How to assign a group to a user? What's the api call? I went through the api documentation but couldn't find the call.
