### ISSUE TITLE
commands in GT06

### ISSUE THREAD

**Issue by cabreu1981** [tananaev/traccar#1930]
hi anton,
i have manage somehow to send commands for engine start/stop in this device,
i tried to send commands in the past days without any luck,
i modified the encoder to send this

    @Override
    protected Object encodeCommand(Command command) {

        switch (command.getType()) {
            case Command.TYPE_ENGINE_STOP:
                return encodeContent("DYD,123456#"); // the numbers are the password of the device, i 
                                      // plan to make it a configurable so you can put yours device password
                                      //  without have to recompile
            case Command.TYPE_ENGINE_RESUME:
                return encodeContent("HFYD,123456#");
        case Command.TYPE_POSITION_SINGLE:
        return encodeContent("DWXX,123456#");

        default:
        Log.warning(new UnsupportedOperationException(command.getType()));
        break;
    }

    return null;
    }

and the engine stop is working, but the engine resume says:
Already in the state of fuel supply to resume,the command is not running!
how can i make it to work, thanks.

**Comment by tananaev** [comment]
I don't know. It sounds like device problem.

**Comment by cabreu1981** [comment]
i have other 9 devices here, i will test with another device and post the results,

 command type: engineResume, id : 3 sent
heres my log content, after the update you made, i'm having this **NegativeArraySizeException **, but the commands anyway works.

i need you to tell me what i have to do so this is not a hack and everyone can use it, 
PD. i'm a c#, siwft  and java for android dev and have a lot of experience with protocols, i developed most of the protocols for his company, actually learning java to give my 5 cents to this proyect.

http://www.positionlogic.com/

2016-05-07 17:30:18 DEBUG: [5A93A5A0: 5023 > 190.167.227.251] HEX: 787816801000000000484659442c313233343536230000e2920d0a
2016-05-07 17:30:18 DEBUG: [5A93A5A0: 5023 < 190.167.227.251] HEX: 787866150000000000416c726561647920696e20746865207374617465206f66206675656c20737570706c7920746f20726573756d652c74686520636f6d6d616e64206973206e6f742072756e6e696e672100000000000000000000000000000000000001001981e50d0a
2016-05-07 17:30:18  WARN: [5A93A5A0] error - NegativeArraySizeException (... < Gt06ProtocolDecoder:240 < ExtendedObjectDecoder:58 < ...)
2016-05-07 17:30:18  INFO: [5A93A5A0] disconnected

**Comment by tananaev** [comment]
Fixed the `NegativeArraySizeException` issue.

**Comment by gbvaz** [comment]
Hi everyone,

I know this is closed but I'm facing exactly the situation as you are @cabreu1981 

I'm trying to send commands to GT06 devices, and I've noticed that the function encodeCommand on this protocol class, on the master branchm only have the TYPE_ENGINE_STOP and TYPE_ENGINE_START implemented. I'm at the point which I'm considering customizing the code, in order to add other commands like the one you've added TYPE_POSITION_SINGLE. I think this could be available to everyone, since I'm not the only one who's facing this need!

How can we proceed?

Thanks!

**Comment by tananaev** [comment]
@gbvaz, are you asking how to implement commands or how to contribute to the project?

**Comment by gbvaz** [comment]
To implement the commands all I would have to do is to include options on the "switch case", recompile and start using, right? What I mean is, since @cabreu1981 and I are trying to use the exact same protocol (GT06) additional commands, why not make his or my changes available to everyone? What I mean is that this topic was closed with the [7ed27b7](https://github.com/tananaev/traccar/commit/7ed27b733d442cb442a8049263fab282b39e5872)  but the fix was related to the NegativeArraySizeException error, not the implementation of the new commands, you see?

**Comment by tananaev** [comment]
You need to add commands to the encoder switch and list it in the protocol class. If you manage to implement commands, please send me a pull request.

**Comment by gbvaz** [comment]
Ok, I'll let you know! Thanks!

**Comment by cabreu1981** [comment]
i have this implemented so this would be awesome to contribute to this proyect.
i opted to put the password in the config file

**Comment by tananaev** [comment]
Please send pull request if you want to include your code in the project.

**Comment by gbvaz** [comment]
That's awesome @cabreu1981 :)

How does this password works? Of all the commands I've sent to my device that have a password as a param is the server configuration command.

**Comment by gbvaz** [comment]
Any news on this matter?

Thanks!
