### ISSUE TITLE
Majority Devices Status - Offline

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#1959]
Dear Anton,

Around 1500 + Devices On Traccar 3.2 Version.

Very rare but twice it occured this week, that around early morning time, the server stops receiving information from devices (Until I restart traccar service).

In the log's there is nothing ubnormal, other than that there is less data. the moment i restart traccar service, the devices are able to post all data/past and current.

Pleas advice how to check/troubleshoot? In terms of hardware its Ubuntu OS and the hardware specs (are under utilized at this moment).

**Comment by tananaev** [comment]
Do you have `resetDelay` set up and connection limits increased?

**Comment by nefertiti007** [comment]
Yes, these are the settings.
<entry key='gt06.resetDelay'>300</entry>
<entry key='status.timeout'>200</entry>

And as for connection limits, its unlimited there is no restrictions set. I also upgraded the hardware specs today.

**Comment by tananaev** [comment]
There are always restrictions on the OS level.

**Comment by nefertiti007** [comment]
Not sure if I got it right, Ubuntu per say does not have any limits. and from the little I did google up and check.

nf_conntrack_max: shows @ 65536

**Comment by nefertiti007** [comment]
Dear Anton,

Okay I think I was looking in the wrong log file to figure out the problem, I checked the wrapper logs and here is the results, sharing the same with you. so that you can suggest/advice me please?

`INFO   | jvm 1    | 2016/05/18 16:37:26 | May 18, 2016 4:37:26 PM org.jboss.netty.util.HashedWheelTimer
INFO   | jvm 1    | 2016/05/18 16:37:26 | WARNING: An exception was thrown by TimerTask.
INFO   | jvm 1    | 2016/05/18 16:37:26 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/18 16:37:26 | 
INFO   | jvm 1    | 2016/05/18 16:40:02 | May 18, 2016 4:40:02 PM org.jboss.netty.util.HashedWheelTimer
INFO   | jvm 1    | 2016/05/18 16:40:02 | WARNING: An exception was thrown by TimerTask.
INFO   | jvm 1    | 2016/05/18 16:40:02 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/18 16:40:02 | 
INFO   | jvm 1    | 2016/05/18 16:50:26 | May 18, 2016 4:50:25 PM org.jboss.netty.util.HashedWheelTimer
INFO   | jvm 1    | 2016/05/18 16:50:26 | WARNING: An exception was thrown by TimerTask.
INFO   | jvm 1    | 2016/05/18 16:50:26 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/18 16:50:26 | 
INFO   | jvm 1    | 2016/05/18 17:35:23 | May 18, 2016 5:35:23 PM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/05/18 17:35:23 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/05/18 17:35:23 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/05/18 17:35:23 | 
INFO   | jvm 1    | 2016/05/18 17:35:24 | May 18, 2016 5:35:24 PM org.jboss.netty.channel.socket.nio.AbstractNioSelector
INFO   | jvm 1    | 2016/05/18 17:35:24 | WARNING: Failed to accept a connection.
INFO   | jvm 1    | 2016/05/18 17:35:24 | java.io.IOException: Too many open files
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.process(NioServerBoss.java:100)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at org.jboss.netty.channel.socket.nio.NioServerBoss.run(NioServerBoss.java:42)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
INFO   | jvm 1    | 2016/05/18 17:35:24 | 	at java.lang.Thread.run(Thread.java:745)
`

**Comment by nefertiti007** [comment]
INFO   | jvm 1    | 2016/05/20 07:59:15 | May 20, 2016 7:59:15 AM org.jboss.netty.util.HashedWheelTimer
INFO   | jvm 1    | 2016/05/20 07:59:15 | WARNING: An exception was thrown by TimerTask.
INFO   | jvm 1    | 2016/05/20 07:59:15 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/20 07:59:15 |

**Comment by tananaev** [comment]
Not sure why you get null pointer exception. Are you sure you are using official Traccar release without any modifications?

**Comment by nefertiti007** [comment]
Yes Yes, Anton its purely official traccar release, with no modification (except web part being disabled)
All queries default, database mysql, traccar 3.2 version.

Also, after that NullPointer exception, after a little while or hour it starts throwing the error I shared above that, connection error. I also checked  OS Limits and increased them too 1500 devices and limits are above 100000 now. for correct user for correct process.

**Comment by tananaev** [comment]
What's the MD5 hash of your `jar` file?

**Comment by nefertiti007** [comment]
I am so sorry, How Do I check that? This is basically a jar file you had sent me after a customization for device status (which was not available in 3.2) but only the later releases.

How or where should i check for md5 hash can  you guide?

**Comment by tananaev** [comment]
I don't remember the modification. Why are you not using official release? Can you please remind me.

**Comment by nefertiti007** [comment]
I have Traccar 3.2 (where there was no availability of device status (online/offline/unknown) back then).

You had done the customization before the release of 3.3 for me and shared the jar file with me. Which I have been using since then.

I would like to update to 3.3 or even the latest, but due to the sheer size of my db being 23GB, and me not have the expertise to now to manage the db upgrade or change, or even take backups without breaking the system or service.

**Comment by nefertiti007** [comment]
Hello Anton,

Its weird this problem never occurred before with same amount of device, average i have added just 10 devices extra in last one week, since this problem occured.

I am a bit lost how to handle this :( down side of not being a programmer

**Comment by nefertiti007** [comment]
Sharing the wrapper log, current scenario. just in-case this might help you help me figure out something.

1. I have increase ulimits for the user/traccar service to 100000 and I have confirmed the same too.

here is what is happening in wrapper log, everytime the server/app starts, and it continues in this pattern. something to do with deviceupdate connection manager in the begining.

`INFO   | jvm 1    | 2016/05/20 21:18:57 | May 20, 2016 9:18:57 PM org.jboss.netty.util.HashedWheelTimer
INFO   | jvm 1    | 2016/05/20 21:18:57 | WARNING: An exception was thrown by TimerTask.
INFO   | jvm 1    | 2016/05/20 21:18:57 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/20 21:18:57 | 	at org.traccar.database.ConnectionManager.updateDevice(ConnectionManager.java:84)
INFO   | jvm 1    | 2016/05/20 21:18:57 | 	at org.traccar.database.ConnectionManager$1.run(ConnectionManager.java:99)
INFO   | jvm 1    | 2016/05/20 21:18:57 | 	at org.jboss.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:556)
INFO   | jvm 1    | 2016/05/20 21:18:57 | 	at org.jboss.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:632)
INFO   | jvm 1    | 2016/05/20 21:18:57 | 	at org.jboss.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:369)
INFO   | jvm 1    | 2016/05/20 21:18:57 | 	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
INFO   | jvm 1    | 2016/05/20 21:18:57 | 	at java.lang.Thread.run(Thread.java:745)
INFO   | jvm 1    | 2016/05/20 21:18:57 | 
INFO   | jvm 1    | 2016/05/20 21:28:12 | May 20, 2016 9:28:12 PM org.jboss.netty.util.HashedWheelTimer
INFO   | jvm 1    | 2016/05/20 21:28:12 | WARNING: An exception was thrown by TimerTask.
INFO   | jvm 1    | 2016/05/20 21:28:12 | java.lang.NullPointerException
INFO   | jvm 1    | 2016/05/20 21:28:12 | `

**Comment by tananaev** [comment]
The issue might be related to the customization. Did I provide you the source code?

**Comment by nefertiti007** [comment]
Unfortunately no, you had not provided the source code. 

What I am thinking is for now I will let the server run as is, Can you help me / advice. then I can try to upgrade to the most latest official release.

But again the problem is, my front end and database is customised a lot (Front-end is php), and I noticed 3.2 to 3.3 I will have to upgrade first, then to 3.5. Another thing is 3.5 has 'groupid' which will clash with the customizations i did in db :( cuz i had also created something similar as groupid earlier.

**Comment by tananaev** [comment]
Are you using Traccar web interface, or only the back-end?

**Comment by nefertiti007** [comment]
Dear Anton, Here is how my setup now is.

Traccar 3.2 Server (Customised with device status)
Traccar Web & API (Disabled)
Own Apache / Php  WEB UI
MySQL DB (Default db structure, but customised with additional columns)

**Comment by tananaev** [comment]
It looks like you are just using the back-end. It should be easy to migrate to the new version. You don't have to change the database structure.

**Comment by nefertiti007** [comment]
Okay, I am gonna try that over the next few days..

**Comment by nefertiti007** [comment]
Dear Anton,

I was able to further troubleshoot and find one more issue, the tracking device port (5023) OS limit is used upto 700 to 800 only on an average.

But I noticed when the traccar client (Tracker android app) on port 5055 just with a single client uses up upto 200+ connections for a single device that sends updates every 10 minute that too.

**Comment by tananaev** [comment]
I guess that you haven't set the connection timeout for 5055 port.

**Comment by nefertiti007** [comment]
You are right anton, I had set it for all the ports I use, but forgot to do that for 5055, I just now set it and restarted the server :) 

Now I think I can be at peace... I am going to upgrade both traccar client to new version and server as well over the next few days, thanks a ton for the usual amazing support :) 

As a thank you, making a small donation your way :) thanks a ton again

**Comment by jaimzj** [comment]
Resolved.
