### ISSUE TITLE
Traccar won't start after system problems

### ISSUE THREAD

**Issue by ilevans** [tananaev/traccar#2047]
Recently my computer encountered issues which have now been rectified. Unfortunately Traccar is not starting and is reporting the following repetitively.

```
INFO   | jvm 1    | 2016/06/24 16:59:17 | INFO 6/24/16 4:59 PM: liquibase: Waiting for changelog lock....
INFO   | jvm 1    | 2016/06/24 16:59:27 | INFO 6/24/16 4:59 PM: liquibase: Waiting for changelog lock....
INFO   | jvm 1    | 2016/06/24 16:59:37 | INFO 6/24/16 4:59 PM: liquibase: Waiting for changelog lock....
```

Any ideas. Traccar V3.4 using MS SQL

After awhile the log shows.

```
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp: 
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error: Encountered an error running main:
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by Wombat (127.0.0.1) since 6/23/16 7:29 PM
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:184)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at liquibase.Liquibase.clearCheckSums(Liquibase.java:1287)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:166)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at org.traccar.database.DataManager.<init>(DataManager.java:65)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at org.traccar.Context.init(Context.java:121)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at org.traccar.Main.main(Main.java:29)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at java.lang.reflect.Method.invoke(Unknown Source)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at org.tanukisoftware.wrapper.WrapperSimpleApp.run(WrapperSimpleApp.java:325)
INFO   | jvm 1    | 2016/06/24 17:04:16 | WrapperSimpleApp Error:   at java.lang.Thread.run(Unknown Source)
STATUS | wrapper  | 2016/06/24 17:04:19 | <-- Wrapper Stopped
```

**Comment by tananaev** [comment]
Looks like Liquibase tables got locked. You need to manually remove the lock from the database table.

**Comment by ilevans** [comment]
Fixed as suggested.
```
update DATABASECHANGELOGLOCK
set locked = 0
```
Many thanks

**Comment by bladika** [comment]
Hi,

I think I have the same problem, but honestly I do not know how to use the above mentioned fix. I get the same wrapperlog than ilevans. My setup is a Raspberry Pi3 (with integrated wifi). The raspberry connects to the network with ethernet + its wifi configured as an access point. Ethernet ip = 192.168.10.10 and Wifi AP ip = 192.168.20.1
I figured out two things:
1. Wrapper log says: liquibase is locked by 192.168.20.1 <- as I mentioned this is the Wifi AP ip
2. If I delete "database.trace.db" and " database.mv.db" and then start traccar server than everything is working. However after a system reboot the problem appears again.

So can you please help me to solve this?
Thanks in advance!

**Comment by tananaev** [comment]
Can you install MySQL on your Raspberry Pi? It would be the best option.

**Comment by bladika** [comment]
Hello tananaev,

it worked! Thanks for the quick help!

**Comment by levin-kelevra** [comment]
Добрый день!
Использую PostgreSQL 9.6.2.
`INFO|25055/0|Service traccar|17-03-06 12:57:44|INFO 3/6/17 12:57 PM: liquibase: Waiting for changelog lock....
INFO|25055/0|Service traccar|17-03-06 12:57:54|INFO 3/6/17 12:57 PM: liquibase: Waiting for changelog lock....
INFO|25055/0|Service traccar|17-03-06 12:58:04|java.lang.reflect.InvocationTargetException
INFO|25055/0|Service traccar|17-03-06 12:58:06| at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at java.lang.reflect.Method.invoke(Method.java:498)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|25055/0|Service traccar|17-03-06 12:58:06|Caused by: liquibase.exception.LockException: Could not acquire change log lock.  Currently locked by 10.0.3.39 (10.0.3.39) since 3/3/17 12:48 PM
INFO|25055/0|Service traccar|17-03-06 12:58:06| at liquibase.lockservice.StandardLockService.waitForLock(StandardLockService.java:190)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at liquibase.Liquibase.clearCheckSums(Liquibase.java:1335)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at org.traccar.database.DataManager.initDatabaseSchema(DataManager.java:143)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at org.traccar.database.DataManager.<init>(DataManager.java:71)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at org.traccar.Context.init(Context.java:198)
INFO|25055/0|Service traccar|17-03-06 12:58:06| at org.traccar.Main.main(Main.java:35)
INFO|25055/0|Service traccar|17-03-06 12:58:06| ... 6 more
INFO|wrapper|Service traccar|17-03-06 12:58:06|waitpid 25055 59136
INFO|wrapper|Service traccar|17-03-06 12:58:06|exit code posix process: 59136 application: 0
`
Посмотрел наличие локов, но их нет.
В БД ошибок нет.
В чём может быть дело?
С H2 всё работает, но хочется Postgre.

**Comment by tananaev** [comment]
Как вы посмотрели локи? У вас Liquibase лок в базе. Обычно это означает что вы остановили сервис во время создания/обновления таблиц в базе.

**Comment by levin-kelevra** [comment]
Я смотрел в pg_stat_activity.
Создал новый инстанс БД, импортнул туда бэкап, но ошибка не исчезла.
И, Вы правы, сбой произошёл во время работы сервера, т.к. вышел из строя блок питания.

**Comment by levin-kelevra** [comment]
Я слепой!
Проапдейтил поле в табличке и всё заработало.
Спасибо!
