### ISSUE TITLE
Default status colour and refresh rate of the device

### ISSUE THREAD

**Issue by Michaal4** [tananaev/traccar#2100]
Hello
It's an awesome project. It is grown a lot since last time i have checked it. Good work. I appreciate it and a lot other people will agree
I got the system up and running. It is now on my spare netbook at home but i will get an VPS in the future.

But i have some basic questions.

What is the default colour of the device? 
I understand that orange in unknown, red disconnected, and green connected and sending data. 
I got an Teltonika fm220 with send period on 30sec and GPS min period on 18sec(for the test) and its most of the time red, and its green for few sec while updating status and then its red again. So i assume that opening and closing of the connection works. But i suspect that while the vehicle is not moving it sends data every 5 minutes, i don't know why yet, i assume its some kind of sleep mode, ill get to that.

When the device is switched off should be orange or red? 
After few minutes of using your android app, the status was green. But when i switched it off (the whole phone) and the status went to orange.

What refresh rate do you suggest for best results?

What data transfer do i need for my sim card (roughly). It is just sending text so it should be much isn't it?
In one of the previous issues you wrote that it shouldn't take around 50MB per month(with 1min refresh rate)

Best regards
Michal

**Comment by Abyss777** [comment]
Hello
I can answer your questions.
There are three statuses of device:
green - it is connected ( network connection is up )
red - network connection was closed (by server or by device)
orange - connection was marked as "Unknown" because of special timeout (it was not closed)

Your device seems send data and closes connection, because of that it is red most of time. There can be some device settings not to close connection after every sending.

Android app uses HTTP protocol and do the same, but there is exclusion for such protocols in code and It becomes orange by timeout.

Refresh rate is depends of your precision requirements.
I think device will need about 1 Mb  a day with 1 min refresh rate.
Do not forget about traffic rounding of your provider. If your device sends data 150-200 bites  and closes connection session will be rounded to 1 Kb or even 10 Kb (depends on provider)

Best regards
Andrey

**Comment by Michaal4** [comment]
Great thank you for the answers.

It is clear now. And what colour should i have in default? How should it be done properly. Should i have all active devices green, isn't it?

**Comment by Abyss777** [comment]
Essentially, if you get information it does not matter which connection status most of time. 
If it is really active and do not sleep it should be green, but not necessarily.

**Comment by tananaev** [comment]
Essentially you want your devices to be green (connected and active). They can turn yellow/orange if there were no message from device for selected interval of time (by default 10 minutes). Red color means that device is disconnected (this status only applies to TCP-based protocols).

**Comment by Michaal4** [comment]
Like i thought.
Any suggestions how to make it green all the time?

**Comment by tananaev** [comment]
You need to configure your device to not disconnect from the server. Not sure if it's actually possible for your device, but hopefully there is an option.

**Comment by Michaal4** [comment]
Thank you. I reckon its not possible so it will stay as it is right now. At least for now

**Comment by stevenbouma** [comment]
Hi, 

Thanks for creating this excellent software!

Like @Michaal4 I'm also using Teltonika hardware, Traccar handles it quite well, but I also have problems with the device status. 

- TCP connections from my clients are closed immediately, and keeping them open is not supported.. (unfortunately)
- Updates from clients are shown briefly in the web UI (a device is marked online, and then immediately offline again)
- The orange/UNKNOWN state is not reached, I assume because all devices receive the status "offline" after an update.

This is sufficient for tracking client locations, but notifications regarding device status are useless (i.e. each update from a client triggers a "device online" and a "device offline" this will drive users crazy)

Would it be possible to make the logic regarding the device state configurable?

I read about a config parameter [protocol].timeout for connection timeout, could we use something like that to mark devices a offline (due to lack of updates and not to loss of connection)?

Many thanks

**Comment by tananaev** [comment]
I have added an exception for Teltonika protocol. It won't set status to "offline" now.

**Comment by stevenbouma** [comment]
Thank you, I have tested this with a new build, and it works like a charm

**Comment by Michaal4** [comment]
Thank you. I will ad this as soon as possible

**Comment by nejck-ikservis** [comment]
I'd say making an exception and closing is not a solution, since Teltonika devices do support persistent connection to server (at least some of them - if you enable FMI).

**Comment by tananaev** [comment]
Implemented configuration option to specify which protocols use non-persistent connections:
```xml
<entry key='status.ignoreOffline'>teltonika,ruptela</entry>
```

**Comment by nejck-ikservis** [comment]
Works for me... although this is more of a device setting than protocol, since it depends on actual device configuration.

**Comment by tananaev** [comment]
Let's see if anybody requests it per device. It's possible to implement, but it would be a bit more complicated.
