### ISSUE TITLE
Granit negative coordinates

### ISSUE THREAD

**Issue by tananaev** [tananaev/traccar#2664]
It seems like for Granit Navigator 04 server decodes coordinates as negative. Not sure if it's a device issue or a server issue. Here is a forum thread:

https://www.traccar.org/forums/topic/координаты-со-знаком-минус/

It's not the first time I hear about it, so I'm starting to suspect that there is some problem on the server side.

@Abyss777, can you please take a look.

**Comment by Abyss777** [comment]
It is not the issue. Just strange behavior of device.

The signs of lat and lon in the same flag as Valid state.
When position is not valid device sets all `flag` byte to zero and lan/lot signs become negative, BUT! also sets old coordinates digits in appropriate place.
Because if that coordinates become negative.

It was the one of reason why I added `coordinates.maxError` correction.

**Comment by tananaev** [comment]
Because it seems like a common issue, I decided to implement a workaround to ignore hemisphere flag if location is invalid. It should work in most of the cases because I'm assuming that the device is mostly used in North and East hemispheres (positive coordinates).
