### ISSUE TITLE
User can change account and notifications in Readonly mode 

### ISSUE THREAD

**Issue by kirantpatil** [tananaev/traccar#2754]
User created in Readonly mode is able to change account and notifications.

Need to remove those links(Account, Notifications) from User page.

**Comment by tananaev** [comment]
That depends on how you define read-only mode. Currently it means that user can't change any shared objects (e.g. devices), but it can change own preferences.

**Comment by tyepez** [comment]
restriction of Readonly should apply only to device modifications or additions. Changes to account and notifications should allowed. custom commands should not allowed in readonly, because with this feature, users will can change configuration on devices.
If you restrict all setting, this account will have demo account property.
Maybe can you add new role as limited user for restrict only device modifications, and allow change on notification and personal account information.

**Comment by tananaev** [comment]
There is already "device readonly" property, which does exactly what you are asking for.

**Comment by tyepez** [comment]
is available in 3.9 version?

**Comment by tananaev** [comment]
No, it's not. It's available starting from 3.10.

**Comment by kirantpatil** [comment]
closing this issue.
