### ISSUE TITLE
Clarification

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2855]
Hello Tanev praise for the work
I wanted some clarification
Are present in various menu a button that read "Attributes" and is not 'very intutivo its use.
As the symbol of the pen goes to modify the I / O device and this menu is called "Alias ​​Attributes"
Then again we find the word "Attributes" in the device menu.
What for?
And 'it duplicates I / O?
Good for anything else? If so dovo I find the commands to use in this menu?
In other menu as Account, Group, Server, always appears at the bottom of a button "Attributes"
What for?
Else on the menu were as attributes and present "Distance" and "Total Distance" how they work and can disable them?
else because I can put one custom map?
If the user wants to switch from Google to the Google Satellite Road or other map as it does?

The web.console control how it works? with which DB?
The command "location.enable", "location.type", "location.key", "location.mcc", "location.mnc" how there are some examples?
the management of email notification as I configure?
You must be configured for each account?
the email of the administrator account alerts all users?
The dates must have the possibility of being set up as YYYY / MM / DD or DD / MM / YYYY
The address is reported incorrectly before the house and then the way

**Comment by tananaev** [comment]
Attributes can store any arbitrary data related to the user, device, server etc.

Distance and total distance are values calculated by the server. Distance is distance from previous location. Total distance is total distance since you've added a device.

Info about custom map:

https://www.traccar.org/map-layers/

It seems like you haven't even tried to search for the answers. Most of your question have been discussed before. Please use search.

As for "web.console", it's only intended for debugging purposes. If you want to more about it, you should check the code.

**Comment by hackerunet** [comment]
Looks like you need a full use guide to learn about traccar, I could suggest for such mcc, mnc values read the GPS manual to check what are those values for.
Yes, traccar is not very intuitive for new users researching about actives real location world, and there is always the alternative affortunately to make your own web interface and mobile application as well.
The best approach to find all your answers is use traccar and see configuration docs.
https://www.traccar.org/documentation/
