### ISSUE TITLE
Notification per device

### ISSUE THREAD

**Issue by tyepez** [tananaev/traccar#2893]
Hi,
Can I set individual notification for each device, instead per account?

Regards,

**Comment by tananaev** [comment]
You can do it for geofences only, because geofences are linked to specific device/group.

**Comment by tyepez** [comment]
This is great for geofences, but I need notifications like motion alarms or ACC, for a few devices.

**Comment by tsmgeek** [comment]
I am looking to address this somehow as its also a problem for me. As there is no defined roadmap its hard to know if someone is already working on this and would not want to double up work.

I am considering a few options.

1. keep the notifications table but add additional columns 
 (deviceid, emailAddress, smsNumber) all default null. If deviceid is blank then this would be legacy or standard notifications for all user devices. Also adding a flag on the device to indicate if its got device specific notifications and if so the NotificationManager will only find notifications if they match userId/deviceId. This is a good option as it reuses all the same classes and APIs and only requires minor changes to NotificationManager/NotificationMail/NotificationSms. If emailAddress/smsNumber are blank/null then the user defaults would be used.

2. add 'notifications_contacts', contacts could be setup and shared across multiple notifications, this way change the one contact and all are changed. This could be in addition to 1 or instead of. It would be easier to do 1 then 2 at later time. This would be ultimately better.

Also changing sendMailAsync/sendSmsAsync to also take Notification model as a parameter so it can process these specific 

The above would be transparent to the webapp due to not changing existing fields and how they are used.

What do you think?

**Comment by tananaev** [comment]
I like the idea of linking to devices, but I think we should make it consistent with other features where we can link to both devices and groups.

**Comment by tsmgeek** [comment]
It may be an idea to split the notifications table into separate device_notifications/group_notifications/user_notifications & deviceuser_notifications. Map everything like has been done with groups.

Would device_notifications be global, ie same across all users that share that tracker? or did you mean user+device notifications?

**Comment by tananaev** [comment]
No, notifications are for users only. It doesn't make sense to have global. But linking should be possible with device and group. Everything is per-user only.

Another nice to have improvement for notifications is ability to limit alarms to a specific one. For example, device let's say device supports SOS and low battery alarms. Currently you can only enable everything together, but ideally user needs to be able to enable selected alarms only (e.g. SOS). This can implemented using attributes.

**Comment by tsmgeek** [comment]
Why not just have notification type 'alarm' to be 'alarm|sos, alarm|lowbatt', each alarm could then have its own email/sms rules etc.
The UI could be changed so that you have to click + and add each notification you want, this would then allow selecting 'Alarm' then additional combo shows up asking what alarm type etc.

**Comment by tananaev** [comment]
You are mixing two completely different things. Type in notification is the type of event in Traccar. All device alarms map to the same "alarm" event.

**Comment by Abyss777** [comment]
IMHO it is better get good clear code and rewrite notifications subsystem than try to save current code to achieve the result.

It is better discuss the logic and come to implementation, than starting from table names

What will be the logic? Closer to device have priority? or if notification set in any point of tree path? Lets look:

Group2 (type=online, web=false)
|
Group1 (type=online, web=true)
|
Device1 (type=online, web=false)

User has (type=online, web=true)

Should be notification sent in this case?
As for me firstly we have to check if user want to get notification of some type, if yes than we should check device tree, but how?

**Comment by tsmgeek** [comment]
@tananaev I know that the type is always 'alarm' but if this had an extension 'alarm|sos', not sure if this is possable if the type is just a string. Then you could have notification based on either just 'alarm' but if there is a '|' then it can check if there is a specific notification setting for that alarm sub-type.

@Abyss777 With notifications at all levels then priority could be a faf. What about an 'inherit' flag, all levels lower than 'User' would automatically be 'Inherit' unless otherwise specified, This would be more akin to RBAC lists.

**Comment by tananaev** [comment]
I don't see any good reason for adding extra prefixes to type. We have attributes that we can use for any additional information.

I don't think we need any inheritance. That's unnecessary over-complication. I was thinking that we can just link Notification object to groups and devices. If it's linked, it means that it applies only for that group/device. If we have two notification objects that affect same device, then user can potentially get two duplicate notifications, but it's up to him to configure it properly to avoid such cases. I don't think we should analyse all notifications and calculate anything based on hierarchy.

Another thought that I had just now is that we can have an extra flag in notification to tell if it applies to all user devices by default. If the flag is "false", then only linked groups/devices are affected. If flag is set to "true", then all user devices are affected except the linked ones.

**Comment by Abyss777** [comment]
Notifications objects have other nature. We can't just link them to devices or groups. We need rethink this feature to apply per device/group.

**Comment by tananaev** [comment]
Why can't they be linked?

**Comment by Abyss777** [comment]
What should mean link of such object to device `8`?
````json
{
 id: 5,
 userId: 1,
 type: online,
 web: true,
 mail: false,
 sms: false,
 attributes: {}
}
````

**Comment by tananaev** [comment]
It means that device `8` comes online, then user `1` will receive a web notification.

**Comment by Abyss777** [comment]
OK, how to NOT get web 'online' notification from device '7' and get mail 'online' notification from device '9' when user `1` can not have multiple notifications of same 'type`?

**Comment by Abyss777** [comment]
If we allow multiple `type`s per user, we need handle 3 level maps/sets user-type-device or something. Updating this will be headache. I believe we should invent something simpler.

**Comment by tananaev** [comment]
Why can't user have multiple notifications of the same type?

I'm open to any suggestions and I all for making it simpler as well.

**Comment by Abyss777** [comment]
> Why can't user have multiple notifications of the same type?

It is how it is working now. (to avoid unneeded duplicates in DB)

If we allow that and allow link notifications to devices. When event comes we need have 3 dimension map/set: "device->type-> set of users" or "user-> type-> set of devices" and still will need iterate through set. It is only to send correct notification and I do not count maps for management.
I do not against, I just say that everything is complicated with notifications we can't just take `ExtendedObjectManager`. We need to think over everything.

Unfortunately, I do not have good suggestion at the moment.

**Comment by tsmgeek** [comment]
A common DB pattern ive used previously is as follows. You just convert all existing to entityType=user and entityID=<userId>. Put an index on both of those columns. Then its just a single notifications table.

id
entityType
entityID
email

**Comment by tananaev** [comment]
@tsmgeek, we are discussing high level architecture of the feature and not the storage format.

**Comment by Abyss777** [comment]
Nevertheless I'm going to investigate this feature.
I'm going to introduce additional boolean flag "always" in Notification model, if user has such notification he will get notifications about all his devices, even if no one notification linked to devices. I think it will probably help migrate from old scheme.

Will see, how complex will be search appropriate Notifications to decide if we should send Event.

**Comment by Abyss777** [comment]
Just thought, we can link Calendar to such notification objects and make them limited by schedule.

**Comment by Abyss777** [comment]
I'm not good in SQL, It would be nice if somebody have time to write request for migration current notifications to standard link scheme.
Basically need to copy two columns `id` and `userId` from `notifications` table into two columns `notificationId` and `userId` to `user_notification` table.

**Comment by tananaev** [comment]
If I understood correctly you need something like this:
```sql
INSERT INTO user_notification (notificationId, userId) SELECT id AS notificationId, userId FROM notifications
```

**Comment by Abyss777** [comment]
Thank you.

PS: looks like I've managed to implement it in not very complex (I would say simple) way. Will send a PR when finish.

**Comment by Abyss777** [comment]
Just not to create separate issue in web repository asking here
What will we do with extra button on devices panel for linking notification to device? There is not spare place.
My suggestion is move all buttons for linking objects to submenu. What are your thoughts?

**Comment by tananaev** [comment]
Agree with your idea. I think it makes perfect sense. Move all linking functionality into a drop-down submenu.
