### ISSUE TITLE
KEY_APPROXIMATE

### ISSUE THREAD

**Issue by jon-stumpf** [tananaev/traccar#2945]
When is it appropriate to set KEY_APPROXIMATE to true?

I assume if I have a means in which to GeoLocate (e.g., GPS, GSM triangulation, etc.), I use Position.setValid(true). And, if the mechanism is not "precise" (e.g., GSM triangulation), I also use Position.set(Position.KEY_APPROXIMATE, true). Is this correct?

**Comment by tananaev** [comment]
At the moment it's only set for geolocated records, which means that the location is not accurate. Possibly we can remove it in future because we can just use "accuracy" value.

Potentially some devices can report this flag directly. For example Traccar Client app can get location using network provider, but then again, we always have accuracy as well.
