### ISSUE TITLE
Traccar v3.9 installation "Error: Can't DROP 'uk_user_token'; check that column/key exists"

### ISSUE THREAD

**Issue by biskandar** [tananaev/traccar#3207]
Hi Traccar Team,

I have just installed traccar version 3.9 , but i found error message below:
```
INFO 6/2/17 1:42 AM: liquibase: ./schema/changelog-master.xml: 
  changelog-3.8::changelog-3.8-dropuniquetoken::author: 
    Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  
    Error: Can't DROP 'uk_user_token'; check that column/key exists [Failed SQL: ALTER TABLE traccar.users DROP KEY uk_user_token]
```
file ./schema/changelog-3.8.xml, below:
```
  <changeSet author="author" id="changelog-3.8-dropuniquetoken" failOnError="false">
    <dropUniqueConstraint tableName="users" uniqueColumns="token" constraintName="uk_user_token" />
  </changeSet>
```

What should i do after this error ? 

Cheers,
/Benny

**Comment by tananaev** [comment]
You can safely ignore this error.

**Comment by glafir** [comment]
I do not ignoring this error (

INFO|5602/0|Service traccar|18-02-07 09:31:36|INFO 2/7/18 9:31 AM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::aut
hor: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: Can't DROP 'uk_user_token'; check that column/
key exists [Failed SQL: ALTER TABLE process.users DROP KEY uk_user_token]
INFO|5602/0|Service traccar|18-02-07 09:31:36|INFO 2/7/18 9:31 AM: liquibase: Successfully released change log lock
INFO|5602/0|Service traccar|18-02-07 09:31:37|[main] INFO org.eclipse.jetty.util.log - Logging initialized @3695ms
INFO|5602/0|Service traccar|18-02-07 09:31:37|java.lang.reflect.InvocationTargetException
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at java.lang.reflect.Method.invoke(Method.java:498)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.rzo.yajsw.app.WrapperJVMMain.executeMain(WrapperJVMMain.java:60)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.rzo.yajsw.app.WrapperJVMMain.main(WrapperJVMMain.java:43)
INFO|5602/0|Service traccar|18-02-07 09:31:37|Caused by: java.lang.NullPointerException
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.traccar.database.BaseObjectManager.getAllItems(BaseObjectManager.java:121)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.traccar.database.GroupsManager.getAllItems(GroupsManager.java:60)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.traccar.database.PermissionsManager.refreshDeviceAndGroupPermissions(PermissionsManager.java:104)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.traccar.database.PermissionsManager.<init>(PermissionsManager.java:56)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.traccar.Context.init(Context.java:364)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  at org.traccar.Main.main(Main.java:35)
INFO|5602/0|Service traccar|18-02-07 09:31:37|  ... 6 more
INFO|wrapper|Service traccar|18-02-07 09:31:37|waitpid 5602 59136
INFO|wrapper|Service traccar|18-02-07 09:31:37|exit code posix process: 59136 application: 231
 1Помощь        2Разверн        3Выход          4Hex            5Перейти        6              7Поиск          8Исходный       9Формат        10Выход

**Comment by tananaev** [comment]
Please don't post random unrelated things. Forum is the right place to ask questions and if you can't find a relevant thread you should create a new one.

**Comment by bamartinezd** [comment]
I have the same error "Can't DROP 'uk_user_token'" and I don't know how to ignore the error
