### ISSUE TITLE
Drivers functionality

### ISSUE THREAD

**Issue by Abyss777** [tananaev/traccar#3332]
Want to discuss the functionality for Drivers
My vision is:

- Implement new model of Driver
  - `name`
  - `rfid` (or `uniqueId`)
  - `company`, `department` etc.

- Implement permissions like for Geofences and Computed Attributes
Driver linked to device mean that he can operate (drive) it
Driver linked to group mean that he can operate (drive) all devices from this group
Driver linked to User mean that User can edit/delete the Driver.

- Extend Device model for one field:
  - `boolean limitDrivers`

- Implement DriversHandler that will generate alarm if Device has `limitDrivers = true` and `position.attributes.rfid` not in list of linked Drivers

- Extend Trip report to set Driver name for every trip

Or it is too complex?

**Comment by tananaev** [comment]
I'm not sure if we need `limitDrivers` at this point. Everything else seems reasonable.

**Comment by Abyss777** [comment]
May be not in a such way but I want to achieve following things:
- Car can be driven by everybody and no alarms should be generated (but if some Driver used RFID his name should be in reports) 
- Car can be driven by only limited list of Drivers, and alarm should be generated if `rfid` not in list and also if device is moving and `rfid` is empty.

Also want to ask, how usually devices send `rfid`? In every position or in special packets? Theoretically might be that no one `rfid` packet came during a trip and we could not determine the Driver.

**Comment by tananaev** [comment]
I think we can start without limitations on drivers. It can be added later, if people request it.

Usually `rfid` is sent only in single position when driver uses it.  By the way, we should probably rename `rfid` to something more generic because it can be any other method of identification, in some cases it can even be a keyboard where driver types their id.

I guess the easiest solution is to copy `rfid` between positions, so we always have it. Maybe there is a better solution?

**Comment by Abyss777** [comment]
We can call it `driverId` or like that. Also I propose do not change protocols to store `rfid` as `driverId`, better implement some handler that will translate protocol ids (rfid and others) to driverId.

Then comes new question, how long will we copy `driverId` until it changes to other? I think it is good for start, in future we can make it more complex, i.e. reset it on ignition off or something.

**Comment by tananaev** [comment]
I think `driverId` would be a bad name. We will have internal `id` and references to it called `driverId`. Maybe it can be something like `driverUniqueId`.  I think we need to change what decoders save because the name is wrong in many cases.

We copy it indefinitely. Next driver will use his key for identification.
