### ISSUE TITLE
Trying to create Calamp Decoder

### ISSUE THREAD

**Issue by fazalkhaliq** [tananaev/traccar#3648]
I'm sorry if I bother you, but I'm trying to implement a CalAmp LMU26G3001-G1000 : LMU2630-01 decoder.

This device uses UDP for connecting and it needs an ACK message so it can keep tracking.

The problem I have is: 

I am receiving the packet data in following and don't know how to deal it.
packet data: `... some binary data ...`

kindly guide.

**Comment by tananaev** [comment]
CalAmp is using binary format, so there is no point in trying to convert it into a readable text. To decode the format you need to get protocol documentation from CalAmp. They have a wiki explaining everything.

**Comment by fazalkhaliq** [comment]
Dear Anton Tananaev,


Thank you for your kind reply. I have wiki access but they mentioned their that the packet is in "BIG Endian" format, but I am receiving data in following format.


? 2 X ?Z ?@Z ?@ ??? d M ? ?? " ^$ B ? Vo ?


As they mentioned on there wiki that the packet format will be follow


Raw Data:
 83 05 01 02 03 04 05 01 01 01 02 00 01 4F B4 64 88 4F B4 64
 88 13 BF 71 A8 BA 18 A5 06 00 00 1333 00 00 00 00 11 11 02
 33 44 44 55 55 66 77 88 99 10 11 ?? 00 ??


kindly guide on this.


Regards,
Fazal Khaliq


________________________________

**Comment by tananaev** [comment]
Obviously they show binary data in HEX format on their wiki. Please stop converting binary data into string and posting it here. It makes no sense.

It seems like you have lack of understanding on how binary data is stored and displayed. I suggest you start with researching those basics before you try to write any code.

I'm closing this issue because it has nothing to do with Traccar project.

**Comment by fazalkhaliq** [comment]
Okay, thanks for your time.
