### ISSUE TITLE
Media access

### ISSUE THREAD

**Issue by kedarnathjimage** [tananaev/traccar#3688]
Hi Anton,

Where to view media files in the application ? 
is their any way to access media files on another server?

**Comment by tananaev** [comment]
No, for now Traccar only stores the files. There is no option to view media files anywhere in the app.

**Comment by kedarnathjimage** [comment]
Ok, Thanks. Can you help me on how to access these media files using browser ? 
i tried directly accessing <<url>>:8082/media but it does not work

**Comment by tananaev** [comment]
It's not exposed via web access.

**Comment by Abyss777** [comment]
I'm thinking of this feature...
My first idea was format `image` position attribute as link and download appropriate file. There are two problems in API I see:
- check permissions. I believe user have to have access to the device to download its media. It is possible to extract `uniqueId` from provided path, but it is bad approach, it is big door for vulnerability.
- gt06 protocol do not store `KEY_IMAGE` attribute in position.

Also may be it makes sens to add some "Media received" event, I think it is hard to find right position in route report with media link.

Just thought another approach, introduce new readonly objects `MediaFile` that stored in DB, that can be enumerated by `deviceId` and downloaded. With may be such fields:
- `id`
- `deviceId`
- `serverTime`
- `fileName`

Files will be still in file system.

@tananaev do you have idea how it should look?

**Comment by tananaev** [comment]
I think server should check permissions. I don't see any problem with using `uniqueId` for it. What is the problem? Media data is always linked to specific device, so if user has access to the device, he should be able to see media files.

Why GT06 is a problem? Is there something preventing us from fixing it?

**Comment by Abyss777** [comment]
OK, lets imagine we implemented API point `/media` that serves GET requests with one parameter `fileName`. It must be very secure, because usually traccar works as root:
- It should not allow read files out from `media.path`
- It should securely extract `uniqueId` from path

I can't guaranty that some file name like `/opt/traccar/media/../../../etc/shadow` or something never trick our protection. Regex or split or what we will use.

I've rechecked gt06 more carefully, looks like no problem to store file name as `image` attribute.

**Comment by tananaev** [comment]
Maybe we can extend servlet that serves static files from folder and check device permissions there. I'm sure Jetty already handles all security issues like parent folders etc.

**Comment by Abyss777** [comment]
Thanks for the tip. It's almost done. Added another `DefaultServlet` to handle media folder and filter to check permissions.
Will send a PR after some polishing.

**Comment by pbreah** [comment]
Excellent feature guys. Any docs for this feature yet?

**Comment by tananaev** [comment]
See linked web app thread.

**Comment by pbreah** [comment]
So to clarify: the feature allows to go into a web directory by passing /api/media/[DEVICE-ID]/

But there is no web UI implementation, no API or events when a media file is received?

**Comment by tananaev** [comment]
It's received as position attribute.

**Comment by pbreah** [comment]
I see, but how can I notify an external app that there was a media file received?

Let's say I'm using the positions API... how can I tell if I received a media file?

**Comment by tananaev** [comment]
As I said, it's in positions attribute.

**Comment by pbreah** [comment]
Ok, let me clarify the question, I got the API docs here:
https://www.traccar.org/api-reference/#/definitions/Position

How will the attribute will be set (object key)? will it be set differently depending on the protocol or media type sent?

**Comment by tananaev** [comment]
It will have one of the following attributes:
```java
    public static final String KEY_IMAGE = "image";
    public static final String KEY_VIDEO = "video";
    public static final String KEY_AUDIO = "audio";
```
with file name as a value.

**Comment by pbreah** [comment]
Thanks Anton!

**Comment by pbreah** [comment]
Last question: 

Will there be an API for media files in the future (getting a link to download, upload elsewhere, delete the file, etc)?

Or do we have to manually create our own app to manage media files ourselves?

**Comment by tananaev** [comment]
There is an API for downloading files.

**Comment by pbreah** [comment]
Just downloading at the moment... This API is not yet in there (https://www.traccar.org/api-reference/) right?, or I'm a not looking right?

and deleting media files? not yet?

**Comment by tananaev** [comment]
Nothing for deleting yet. For downloading we already discussed it above. You have access to the folder.

**Comment by tananaev** [comment]
What do you mean manually pulling? It's the same API.

**Comment by pbreah** [comment]
Means I have to build my own download link, as there is no API I can use from here (https://www.traccar.org/api-reference/) that I can pass the deviceId and Id of the position that the media file came from, to get a download link.

**Comment by tananaev** [comment]
You always build your own link with any other Traccar API. There is no difference, other than it's not in the document that you keep referring to.

**Comment by pbreah** [comment]
Right. But this is not what I meant to say.

On production you wouldn't use the Traccar server as a file server - right?

So, picture this scenario:

- I have the Traccar server
- I have an API server with my business logic
- I have a file server (S3 or other provider)
- I have clients that pull info from my API server
- My API server connects with Traccar to serve info to my clients.

Since I don't want to have my Traccar server be a file server too (as it can be more expensive that way) I want Traccar do one of these two things:

- Have a driver that could upload these files directly to a server such as S3 - then I can use the S3 API to serve these files to my clients - a perfect scenario.

Or

- Have a way for the Traccar API to generate a link for me so I don't need to pass user credentials around, or worse my Traccar admin access to other services in my stack. Because it is better to keep the access centralized instead of having access spread into different services.

This "generated download link" can have an expiring token that I can pull from my API server, and pass to my file server to download the file. In this case my file server doesn't need credentials as it has a "one time use" token to download the file from Traccar. Then Traccar "could" delete the file from the server after a successful download. Each client would have a dedicated folder named the same as the device ID (On my S3 bucket) and I can use a similar logic you guys Implemented, but ON my file server.

What are the advantages?

- I can keep my credentials centralized (On my API server only).
- I can scale my capacity easily as my file server manages what it does best - files.
- Separation of concerns - I now can manage my files outside Traccar and be served to the clients.

The driver approach would be ideal, as I could upload directly to S3 (for example) and not use my Traccar server bandwidth. But if you guys consider the dynamic link with single use token, that also helps.

Hope this helps understand the use case I'm picturing with the feature you guys started. I would love to contribute, but I don't do Java.

Again I appreciate what you guys have built so far, but this would make it production friendly if considered.

Thank you guys!

**Comment by tananaev** [comment]
If you want to discuss it further I suggest you create a separate forum thread.
