### ISSUE TITLE
[ERROR] "liquibase: Waiting for changelog lock" Please help

### ISSUE THREAD

**Issue by Obaid-ur-Rehman** [tananaev/traccar#3792]
I am getting this message in wrapper.log file. Please help me

**Comment by tananaev** [comment]
It means that database got locked. Usually it happens if you kill or force stop the service while it's running database migration. You need to manually unlock it or restore database from backup.

This issue has been discussed multiple times on forum, so I would recommend searching there for more info. Also, for generic questions like this you should use forum. GitHub is only for development-related discussions.
