### ISSUE TITLE
Is there any way to make GT06 keep sending location while in park mode?

### ISSUE THREAD

**Issue by xqoyx** [tananaev/traccar#532]
Hi, just like the tittle says, i have a question, is there any way / any param to make GT06 keep sending location while in park mode? i know, it was GT06 features to disable sending location data while car is in park and didn't move, but can i force GT06 to keep sending location data to server? (due to some GPS Tracking device have some kind of GetPosition feature)

Thanks

**Comment by vkumarOST** [comment]
Hi tananev 

Am Building a GPS tracking application. am new to socket programming. am able to connect with my gps its GT06 but not able to read data can you send me the sample code. so that i will understand how to read data so that i will code to by myself for my customise requirement. all i need is to recive data to my application and how to convert
