### ISSUE TITLE
Adding device AVL-901(C) from GoPass for testing

### ISSUE THREAD

**Issue by Portand** [tananaev/traccar#538]
Dear Anton:

I want to test the device AVL-901(C) from GoPass, I´ve installed the software, and I´ve added the device IMEI, but I dont know how i can configuere the port. The device by default is 3000. I need to setting my device with IP address of server and  port, What port I must use.. I will report to you the test results. If all works fine, I will send you a donation.. Thanks for your effort, support and time.

**Comment by ykuendig** [comment]
sorry for hijacking this thread, but maybe its related. i tried to connect a gopass AVL-900(M) and same (nothing) happend to me. unfortunatly the device is sending only udp packets to port 3000. i can redirect the port. but prob. because of udp nothing is logged. if i sent to port 5082 there are reactions, but no usefull result. the tracker seems to send nmea data and has a GPRMC and GPGGA data-block.
Something, yoou can help with?

**Comment by warlockopy** [comment]
#2026 is a similar case. No solution yet?
