### ISSUE TITLE
Create a Device by directly inserting data into the database. 

### ISSUE THREAD

**Issue by hussainnagri** [tananaev/traccar#565]
I am trying to link Traccar and another system, for that I need to create Devices in to Traccar by directly inserting values into the database (or calling a API if their is any ), I tried this by inserting values in the table 'devices' and then linking that device with a user by inserting a row in 'users_devices'. Other than these two entries I didn’t do anything else. While I use the Traccar Web Service I still don’t see any device that I created. I think I am missing some entries. can anyone Help ?

**Comment by gbvaz** [comment]
Hi, I know this is an old topic, but I'm having the same problem. I'm using traccar version 3.5 with another system so I have to insert into device and user_device tables, exactly as shown by @hussainnagri, then when I call a method using the api, say positions method for example, using the user associated with my device, I get a permission denied message. Should I use the api to insert the device in order to avoid this problem? Thanks!

**Comment by Abyss777** [comment]
Hello
It is always better to use API to add devices. It is do all needed changes and updates all internal caches.

Explanation why situation happens: There is also "permission" cache and it is not updating like "device" cache by timeout and "unknown" device. It updates only on some significant changes in devices, groups or permissions made via API. 
If you add device to DB directly traccar just allow receive positions from that device.

**Comment by gbvaz** [comment]
@Abyss777 I've upgraded to 3.6, and I've started using the API in order to grant permission to existing devices with /api/permissions/devices endpoint. The problem is that it looks like that even using the API the cache is not updated, I'm still getting permission denied error on my traccar web while trying to see any reports of historical positions:

`{"details":"Device access denied - SecurityException (PermissionsManager:133 < PositionResource:44 < ...)","message":"Device access denied"}`

**Comment by tananaev** [comment]
You can check database, but API should work because original web interface uses it and everything works.

**Comment by gbvaz** [comment]
Database is correct, it all matches up but I still can't see historical data. I'm refactoring my code to start using the /api/devices too, just in case. The tests I did using Postman indicated that the /api/devices set the correct permission, but  apparently the /api/permissions/devices only inserts the row on the database and it doesn't update the cache. Thank you for you time and help :)

**Comment by Abyss777** [comment]
Ask just in case. Are you sure you are trying to get history from the same user that you just give permission?

**Comment by tananaev** [comment]
Also, make sure you are using correct device id.

**Comment by gbvaz** [comment]
@Abyss777 Yes I am, the user is the same. @tananaev Yes, the device is correct. I've finished the change, now I'm inserting new devices via API. It really seems to be a problem with the permission endpoint. Anyway, everything is working now, thanks!

**Comment by tananaev** [comment]
I just checked the code and there seem to be no difference in the code. Both API calls refresh all permissions.

**Comment by gbvaz** [comment]
That's really odd..

**Comment by tananaev** [comment]
Just tested on local server and everything works perfectly. Are you sure you are using INTERNAL DEVICE ID?

**Comment by gbvaz** [comment]
I'm absolutely sure.. Just to be clear, I was inserting a device manually in the database, then using the api to update it's permission. This way didn't work at all. Now I'm using the api to insert the device, so I don't need to update the permission again. This way is working perfectly fine. So, I don't think this should be a matter to be worried about.

**Comment by tananaev** [comment]
I see. There might be a problem when you insert device manually. It takes some time to update cache, so permissions refresh might not work as expected because it can't find the device. Using API for everything is preferred.

**Comment by gbvaz** [comment]
Sure, thanks!

**Comment by meneva** [comment]
can anybody give an example function for addDevice via traccar api ?
using javascript ajax method will be good enough.
