### ISSUE TITLE
Traccar dont create any table on mysql server

### ISSUE THREAD

**Issue by N4gato** [tananaev/traccar#761]
Hello !
well i'm on Ubuntu 14.04 , I installed traccar, it's start fine. I install MySQL server then i create a DB . after that i configured the traccar.cfg with my server parameters. 
In the doc it mentioned that the traccar will creat tables for me. In real, i find no tables in the database. 
Any help ?

**Comment by theMastablasta** [comment]
Having same issue here, no tables are created. 
I am using Netbeans and MySQL. MySQL has a database (which is working) and is connected. The only error I received was the SSL and this was fixed by setting it to false. If I open the webUI I can see my device with all data up to date.
traccar.xml was changed to:
<entry key='database.driver'>com.mysql.jdbc.Driver</entry> 
<entry key='database.url'>jdbc:mysql://localhost:3306/t1000?allowMultiQueries=true& amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=ANSI_QUOTES</entry>
<entry key='database.user'>MYUSERNAME</entry> 
<entry key='database.password'>MYPASSWORD</entry>
Thanks for any help.

**Comment by tananaev** [comment]
@theMastablasta, please create a new issue and provide more details (e.g. log files).

**Comment by theMastablasta** [comment]
Ok, done

**Comment by karthikbalu** [comment]
Hi
I managed to start the traccar server using external mysql with the help of config file as below
I can access the web ui without any issues but not able to see any tables or data created on mysql server

`<?xml version='1.0' encoding='UTF-8'?>

<!DOCTYPE properties SYSTEM 'http://java.sun.com/dtd/properties.dtd'>

<properties>

    <entry key="config.default">./conf/default.xml</entry>
<entry key='web.debug'>true</entry>

<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
<entry key='database.url'>jdbc:mysql://host:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true&amp;useUnicode=yes&amp;characterEncoding=UTF-8&amp;sessionVariables=sql_mode=''</entry>
<entry key='database.user'>username</entry>
<entry key='database.password'>password</entry>
</properties>`


log file has not very useful and no error
`
/opt/traccar # more logs/tracker-server.log 
2017-08-23 14:59:22  INFO: Operating system name: Linux version: 3.10.0-327.el7.x86_64 architecture: amd64
2017-08-23 14:59:22  INFO: Java runtime name: OpenJDK 64-Bit Server VM vendor: Oracle Corporation version: 25.111-b14
2017-08-23 14:59:22  INFO: Memory limit heap: 843mb non-heap: 0mb
2017-08-23 14:59:22  INFO: Character encoding: UTF-8 charset: UTF-8
2017-08-23 14:59:22  INFO: Version: 3.12-SNAPSHOT
2017-08-23 14:59:36  INFO: Starting server...
/opt/traccar # 

`

also there is no wrapper.log file in log folder


Please help me thanks

**Comment by tananaev** [comment]
@karthikbalu, please don't comment on old closed threads.

As for the issue, if there is no wrapper log file, it means that server is not running or you are doing something wrong.
